# Generated by Django 3.0.5 on 2020-04-29 19:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0002_auto_20200429_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='corpo',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
