# Generated by Django 3.0.5 on 2020-04-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0004_auto_20200429_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(default='', upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
