# Generated by Django 3.0.5 on 2020-04-29 21:22

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0006_auto_20200429_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[200, 200], upload_to='uploads'),
        ),
    ]
