# Generated by Django 3.0.5 on 2020-04-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0012_auto_20200430_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
