# Generated by Django 3.0.5 on 2020-04-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0013_auto_20200430_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
