# Generated by Django 3.0.5 on 2020-04-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0014_auto_20200430_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
