# Generated by Django 3.0.5 on 2020-04-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0015_auto_20200430_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.TextField(max_length=400),
        ),
    ]
